# Generated by Django 4.2.15 on 2024-09-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_snack_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Snack_Profile',
        ),
    ]
